:experimental:
:Omega: &#937;
:nrf-toolchain: v2.6.1
:nrf-sdk: 2.6.1
= Lab guides for _Introduction to Embedded Systems_
John M. Larkin <jlarkin@whitworth.edu>
:navtitle: About

This is a collection of lab guides for the course _EN 173: Introduction to Embedded Systems_ taught by John Larkin at https://www.whitworth.edu[Whitworth University]. The development board used throughout these guides is https://www.nordicsemi.com/Products/Development-hardware/nRF52840-DK[Nordic Semiconductor's nRF52840 DK]. In addition, Nordic Semiconductor's https://www.nordicsemi.com/Products/Development-software/nRF-Connect-SDK[nRF Connect SDK] and the associated https://www.nordicsemi.com/Products/Development-tools/nRF-Connect-for-VS-Code[Visual Studio Code extension] are used to provide a development environment that is relatively accessible for a student first encountering embedded systems. However, the course also targets the https://zephyrproject.org/[Zephyr RTOS] which is designed to be portable across a broad selection of platforms so much of what is found in these guides should be applicable to other microcontrollers with only minor changes.

.xref::lab1.adoc[Lab 1 -- Getting Started]
[%collapsible]
====
****
In this set of activities you will:

* install the development environment,
* create a simple program to flash an LED on the development board, and
* transfer that program to the development board.

Additional hardware required: none
****
====

.xref::lab2.adoc[Lab 2 -- Basic Digital Input and Output]
[%collapsible]
====
****
In this set of activities you will:

* use a button internal to the development board,
* connect the development board to external circuit elements (LEDs and resistors),
* modify the devicetree to enable use of additional digital output pins, and
* use an oscilloscope to observe the output of a GPIO pin.

Additional hardware required:

* two LEDs (described as red and green in instructions)
* two 330 {Omega} resistors
* oscilloscope (instructions describe usage of Digilent's _Analog Discovery 2_)

WARNING: **Your Turn** section is not complete

****
====

.xref::lab3.adoc[Lab 3 -- Going Deeper with Digital Input and Output]
[%collapsible]
====
****
In this set of activities you will:

* set the state of multiple output pins with a single command,
* modify the devicetree to enable use of additional digital input pins, and
* use an external slide switch and momentary push button.

Additional hardware required:

* two LEDs (described as red and green in instructions)
* two 330 {Omega} resistors
* slide switch (SPDT)
* momentary push button (SPST)

WARNING: Multiple areas are not complete

****
====
