:sectnums:
:source-language: c
= Lab 1

== Installing the tools

== An embedded "`Hello, world`"

On a general purpose computer the stereotypical first program in a language displays `Hello, world!` on the screen. In the world of microcontrollers the equivalent is to flash an LED. This is also called a heartbeat program. It is a simple way to indicate that your microcontroller is alive and you are able to transfer a simple program to it. Most development boards will have one or more integrated LEDs, so no external connections are necessary. The https://www.nordicsemi.com/Products/Development-hardware/nRF52840-DK[Nordic Semiconductor nRF52840 DK] that will be our example development board has four integrated LEDs. The first program will flash one of these, labeled LED1, off and on forever (or as long as the microcontroller is powered). Flow charts are a useful tool for planning and documenting code, so before we jump into the code itself we start with a flow chart for this first program.

```mermaid
graph TD
  A("main()") --> B[Initialize LED1]
  B --> C{Is it true?}
  C --> |yes| D[Turn on LED1]
  D --> E([Sleep 250 ms])
  E --> F[Turn off LED1]
  F --> G([Sleep 250 ms])
  G --> C
```

=== Creating a new application

=== Entering the code

Replace the contents of `main.c` (in the `src` folder) with the following code. **Always** type the code from these lab guides into the editor yourself; don't copy and paste it. You will pay more attention to the details of the code and learn it better if you type it.

[source]
[[program-blink-internal-LED]]
.A program to blink an internal LED.
----
/********************************
 * Heartbeat program
 * 
 * Flashes an internal LED
 *******************************/
#include <zephyr/kernel.h>        // <1>
#include <zephyr/drivers/gpio.h>

#define LED0_NODE DT_ALIAS(led0)  // <2>
static const struct gpio_dt_spec led = GPIO_DT_SPEC_GET(LED0_NODE, gpios);  // <3>

int main() {  // <4>
	gpio_pin_configure_dt(&led, GPIO_OUTPUT_ACTIVE);  // <5>
	while (true) {
    gpio_pin_set_dt(&led,1); // 1 = ACTIVE = ON
    k_msleep(250);
    gpio_pin_set_dt(&led,0); // 0 = INACTIVE = OFF
    k_msleep(250);
  }
}
----
<1> Zephyr is designed to be lightweight so only the components you need are included. These import Zephyr's Kernel and GPIO APIs.
<2> Information about the hardware is stored in something called the devicetree. This looks up the identifier for the LED associated with the alias `led0`.
<3> This creates a container called `led` that holds information about a GPIO pin.
<4> The Zephyr RTOS looks for a user-defined function called `main` to run after it completes its start-up. This is often the heart of your application.
<5> The GPIO pin linked to LED1 is configured as an output and set to be in the active (on) state.
