name: Content Feedback
description: Provide feedback on page content
body:
  - type: input
    id: pageurl
    attributes:
      label: Page reference
      description: Partial URL of the page (should autofill)
    validations:
      required: true
  - type: checkboxes
    id: feedback-type
    attributes:
      label: Type of feedback
      options:
        - label: Error in source code
        - label: Spelling or grammar errors
        - label: Lack of clarity
        - label: New content request
        - label: Other
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      placeholder: Tell me more.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Thanks for taking the time to provide feedback.

