name: Content Feedback
description: Provide feedback on page content
title: "[Feedback]: "
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to provide feedback.
  - type: input
    id: pageurl
    attributes:
      label: Page reference
      description: Partial URL of the page (should autofill)
    validations:
      required: true
  - type: checkboxes
    id: feedback-type
    attributes:
      label: Type of feedback
      options:
        - Error in source code
        - Spelling or grammar errors
        - Lack of clarity
        - New content request
        - Other
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      placeholder: Tell me more.
    validations:
      required: true

